# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo
    parallelism: 1

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - run: mkdir -p test-reports test-artifacts
      - run: which python
      # Step 2: create virtual env and install dependencies
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics  --ignore E501,E265,W293,W291 --per-file-ignores="__init__.py:F401"
            circleci tests glob "tests/**/*.py" | circleci tests split > /tmp/tests-to-run
            pytest
      - store_test_results:
          path: test-reports/  
      - store_artifacts:
          path: htmlcov/
          destination: tr1